[workspace]
members = [
    "helloworld",
    "primitives",
    "custom-types",
    "variable-bindings",
    "types",
    "conversion",
    "expressions",
    "flow-of-control",
    "functions",
    "modules",
    "cargo/foo",
    "cargo/bar",
    "attributes",
]
default-members = [
    "helloworld",
    "primitives",
    "custom-types",
    "variable-bindings",
    "types",
    "conversion",
    "expressions",
    "flow-of-control",
    "functions",
    "modules",
    "cargo/foo",
    "cargo/bar",
    "attributes",
]
resolver = "2"
