[workspace]
members = ["helloworld", "primitives", "custom-types", "variable-bindings"]
default-members = [
    "helloworld",
    "primitives",
    "custom-types",
    "variable-bindings",
]
resolver = "2"
